database/Helpers/notifications-model.js
database/Helpers/teamMember-model.js
database/Helpers/user-model.js
routes/messageRouter.js
routes/teamMemberRouter.js
routes/userRouter.js

Internal API functionality for `users` endpoints updated, fixed when necessary, and fine-tuned in a couple places. All userRouter endpoints and user-model helper functions tested and verified to have expected behavior via Postman.

feat/Improve user router/helper functionality

---

routes/teamMemberRouter.js

Fixes a bug with deployment
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

fixes accidentally deployed merge conflict

---

database/Helpers/notifications-model.js
notificationSystem/sendEmailNotifications.js
notificationSystem/sendTextNotifications.js

Variable names in sendEmail/TextNotifications updated based on standardized schema now throughout the backend, shortened up notification-model slightly since all properties are valid to send back
Bring notificationSystem up to speed with backend schema naming conventions now throughout the rest of the app. Shortened up code in notification-model slightly based on zoom conversation with @ajb85 , who has further plans to increase DRYness of notification code once immediate concerns are addressed. Changed 0/1 boolean values (needed for MySQL to work) over to true/false version for use with postgreSQL.
No relevant testing to be done until notifications system undergoes its testing phase: naming updates only.

fix/Update schema conventions in notificationSystem

---

notificationSystem/sendSlackNotifications.js
routes/slackRouter.js

Slack API is working as intended with migrations to the database and a test route to send messages.  I'm PR'ing so other team members can play around with the message format and find one we like.  Code isn't quite 100% as the database still needs to be updated that the message sent successfully.
Manual (postman)

Test route and database migrations added

---

database/Helpers/trainingSeries-model.js
database/migrations/20190501152707_add_slack_columns.js
routes/trainingSeriesRouter.js

Finish converting schema names in messagesRouter and related files over from "posts" to "messages" as expected, no other changes made.
Tested locally in conjunction with soon-to-be made PR for FE.

fix/messages API converted from "posts"

---

routes/stripeRouter.js
server.js

uncommented stripe in the server, added env variable on heroku, and exported the stripe router so that everything works for production.
on my local machine

:bug: got stripe to work on production

---

notificationSystem/sendSlackNotifications.js
notificationSystem/sendTextNotifications.js
routes/slackRouter.js
server.js

Adds the majority of the endpoints for the Slack API, just needs 2 more endpoints for oauth.
Manually, locally

Slack API Endpoints

---

models/db/users.js

When we changed the Data Model in #37, we didn't update the user model to handle the new names for certain columns. This prevents us from logging in even though a client makes a valid request.
This Pull Request will resolve that issue, though it won't work completely until @DaftBeowulf completes the work he's doing on validaton/migrations.
This was tested locally, but cannot be tested by anyone else until @DaftBeowulf finishes his work on JOI validation.

Alter User database handler to reflect v2 Data Model

---

controllers/slack.js
models/db/tokens.js
yarn.lock

Adds the slack API oauth endpoint and creates the db model for tokens.
Tested manually locally

Ww slack api

---

controllers/message.js
controllers/notification.js
controllers/responses.js
controllers/teamMember.js
controllers/trainingSeries.js

.first() methods chained onto all calls in the controllers meant to grab a single resource by id--was not added in the model queries because the one find call should be able to return ALL resources or just one, depending on what the controller says. Will fix FE behavior of receiving [{resource}] when grabbing a single resource instead of {resource}
Simple change and knew it needed to be made after debugging FE issue with @GannonDetroit

:bug: Adding .first() calls

---

controllers/slack.js
controllers/teamMember.js
controllers/user.js
jobs/notifications/send/slack.js
middleware/dataValidation.js
models/db/teamMembers.js
models/schemas.js

while auditing the frontend team member actions and reducers and then the subsequent code purge that came from the massive errors issues, a few things on that backend needed to be updated to allow those code changes
local machine

:recycle: necessary changes from the teamMember Audit

---

controllers/message.js

Add a route to get all messages for a training series, provided the token provided matches the user who owns the series.
Locally, postman

Added route to get messages for a training series

---

controllers/auth.js
controllers/message.js
models/db/messages.js
models/migrations/20190506173831_data_model_v2.js
models/schemas.js

This commit includes fixes for messages/adds column for days_from_start.

fixes to messages backend

---

controllers/message.js
models/db/messages.js

Minor tweaks to the BE to work with FE refactor changes.
Manually

Updates the backend to work with FE changes

---

controllers/stripe.js

Stripe endpoints now correctly update users table to persist changes made in FE on account page. Mostly involved making sure User.update functions were being handled asynchronously with the correct syntax for the filter being passed in. Combined with this FE PR https://github.com/labs12-training-bot-2/labs12-training-bot-2-FE/pull/56, completes full functionality for Account page with upgrading/downgrading subscription from any previous type, the relevant info being displayed, and changes persisting by making sure the changes were correctly observed in the database here. 
Locally in the browser, with changes verified in my local psql database.

:bug: Updating stripe controller

---

controllers/responses.js

Prevents bot messages from being saved
Manual test

Minor tweak to filter out bot messages

---

models/db/notifications.js

This documents the Notifications model using JS Doc comments. Our goal is to ensure that someone completely unfamiliar with our project would be able to step into this file and understand what everything does

Document the Notifications Model

---

models/db/messages.js

This documents the Messages model using JS Doc comments. Our goal is to ensure that someone completely unfamiliar with our project would be able to step into this file and understand what everything does

Document the Messages model

---

models/db/responses.js

This documents the Responses model using JS Doc comments. Our goal is to ensure that someone completely unfamiliar with our project would be able to step into this file and understand what everything does

Document the Responses model

---

models/db/tokens.js

This documents the Tokens model using JS Doc comments. Our goal is to ensure that someone completely unfamiliar with our project would be able to step into this file and understand what everything does

Document the Token model

---

middleware/dataValidation.js

This documents our custom data validation middleware using JS Doc comments. Our goal is to ensure that someone completely unfamiliar with our project would be able to step into this file and understand what everything does.

Document custom Data Validation middleware

---

middleware/errorHandling.js

This documents our custom error handling middleware using JS Doc comments. Our goal is to ensure that someone completely unfamiliar with our project would be able to step into this file and understand what everything does.

Document custom Error Handling middleware

---

ecosystem.config.js
jobs/notifications/index.js
jobs/notifications/lib/common.js
jobs/notifications/lib/notify.js
jobs/notifications/lib/senders/email.js
jobs/notifications/lib/senders/slack.js
jobs/notifications/lib/senders/sms.js
jobs/notifications/lib/wipeFailed.js
server.js

This PR accomplishes a few things. 
1. It changes the Notification cron job to an IIFE so it can be called by PM2 directly as a separate process from the API itself
2. It updates PM2 to manage the Notification cron job
3. It thoroughly documents the code for the Notifications job, including all sender functions and helper functions.
Tested manually locally but having the job run every second. However, it will run every 10 minutes as we expect it to.

Document the Notifications cron job

---

controllers/stripe.js

the endpoint that allows for updating the subscription plan wasn't clear enough, updated the lanaguage to make it more clear

:memo: small clarification to stripe docs

---

models/db/trainingSeries.js

finished docs for the training series model

:memo: finished docs for training series model

---

app.json
docs/README.md
docs/prerequisites.md
docs/setup.md
knexfile.js

This Pull Request introduces the "docs" directory, and attempts to provide guidance on configuring the appropriate third party services and local development environment with Training Bot.
It also updates our Database URL and production config var to reflect the reproducible structure of Heroku.
I'll need @ajb85 and @GannonDetroit to follow up by writing detailed docs in the `docs/prerequisites.md` file for Slack and Stripe, respectively.
Documentation change only. No testing needed.

Write detailed setup documentation

---

controllers/trainingSeries.js
models/db/trainingSeries.js

:memo: finished docs for training series controller

---

.github/README.md

:memo: added the training series info to the readme

---

docs/prerequisites.md

Docs and such.
Tested thoroughly on my machine.  Can confirm the text just sits there.
50/50 chance it breaks everything though.

Been done written them there docs

---

controllers/stripe.js

:recycle: changing from test to production

---

docs/database.md

Docs properly linked to intended file in repo, but without expected line highlighting. This fixes that.
By clicking dem links.

:memo: Fixes links in database docs
